# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
- docker build -t udagram-api-feed ./udagram-api-feed
# Do similar for other three images
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t reverseproxy ./reverseproxy
- docker build -t udagram-frontend ./udagram-frontend

# Tagging
- docker tag udagram-api-feed myactivdock/udagram-api-feed:v1
# Do similar for other three images
- docker tag udagram-api-user myactivdock/udagram-api-user:v1
- docker tag reverseproxy myactivdock/reverseproxy:v1
- docker tag udagram-frontend myactivdock/udagram-frontend:v1

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push myactivdock/udagram-api-feed:v1
# Do similar for other three images
- docker push myactivdock/udagram-api-user:v1
- docker push myactivdock/reverseproxy:v1
- docker push myactivdock/udagram-frontend:v1

# Tip: Use different tags each time you push images to the Dockerhub.