language: node_js
node_js:
- "stable"
env:
  - DOCKER_COMPOSE_VERSION=1.4.2
dist: trusty
branches:
  only:
    - master
services:
    - docker
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t reverseproxy ./reverseproxy
  - docker build -t udagram-frontend ./udagram-frontend
# Tagging
  - docker tag udagram-api-feed ./udagram-api-feed:v1
# Do similar for other three images
  - docker tag udagram-api-user ./udagram-api-user:v1
  - docker tag reverseproxy ./reverseproxy:v1
  - docker tag udagram-frontend ./udagram-frontend:v1

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ./udagram-api-feed:v1
# Do similar for other three images
  - docker push ./udagram-api-user:v1
  - docker push ./reverseproxy:v1
  - docker push ./udagram-frontend:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ./udagram-api-user:v2
  - docker push ./udagram-api-feed:v2
  - docker push ./reverseproxy:v2
  - docker push ./udagram-frontend:v2
